name: kino_ne
description: "経木ノートアプリ - 木の音、木の根。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1


  sqflite: ^2.4.1
  path: ^1.9.1

  intl: ^0.20.2
  uuid: ^4.5.1
  riverpod_generator: ^2.3.5
  collection: ^1.19.1
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.2
  icloud_storage: ^2.2.0
  shared_preferences: ^2.3.2
  device_info_plus: ^11.2.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

  build_runner: ^2.4.13

  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    -  assets/images/
    -  assets/images/bg_images/